"""First revision

Revision ID: 0dd6a8311f21
Revises: 
Create Date: 2023-09-13 14:59:27.623368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd6a8311f21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_user_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_publications_publication_id', table_name='publications')
    op.drop_table('publications')
    op.drop_table('countries')
    op.drop_table('comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('comment_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('publication_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.publication_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('countries',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name_common', sa.VARCHAR(), nullable=True),
    sa.Column('name_official', sa.VARCHAR(), nullable=True),
    sa.Column('independent', sa.BOOLEAN(), nullable=True),
    sa.Column('languages', sa.VARCHAR(), nullable=True),
    sa.Column('region', sa.VARCHAR(), nullable=True),
    sa.Column('subregion', sa.VARCHAR(), nullable=True),
    sa.Column('flag_svg', sa.VARCHAR(), nullable=True),
    sa.Column('flag_icon', sa.VARCHAR(), nullable=True),
    sa.Column('population', sa.INTEGER(), nullable=True),
    sa.Column('gini', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publications',
    sa.Column('publication_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('publication_id')
    )
    op.create_index('ix_publications_publication_id', 'publications', ['publication_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('register_time', sa.FLOAT(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['country'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###
